package com.example.pizzarecipes;

public class Utils {
    public static final String MARGHERITA_PIZZA_TITLE = "Margherita pizza";
    public static final String MARGHERITA_PIZZA_DESCRIPTION = "The ultimate pizza pie, in our opinion? The pure and simple pizza Margherita. This iconic Italian pie is truly something special: stretchy mozzarella cheese, garlicky pizza sauce, and peppery basil all piled on a chewy, charred crust. We’re so enamored with it that we’ve spent years researching authentic Italian pizza methods, interviewing experts, and even traveling to Naples Italy to taste it for ourselves! Here are the secrets to making the very best margherita pizza.";
    public static final String MARGHERITA_PIZZA_RECIPE = "1. Make the pizza dough: Follow the Best Pizza Dough recipe to prepare the dough. (This takes about 15 minutes to make and 45 minutes to rest.)\n" +
            "2. Place a pizza stone in the oven and preheat to 500°F. OR preheat your pizza oven (here’s the pizza oven we use).\n" +
            "3. Make the pizza sauce: Cut the garlic into a few rough pieces. Place the garlic, tomatoes, olive oil, oregano and kosher salt in a blender. Blend until fully combined. (You’ll use about ⅓ cup for the pizza; reserve the remaining sauce and refrigerate for up to 1 week.)\n" +
            "4. Prepare the cheese: If using fresh mozzarella cheese, slice it into ¼ inch thick pieces (see the photos of the pre-baked pizza above). If it’s incredibly watery fresh mozzarella (all brands vary), you may want to let it sit on a paper towel to remove moisture for about 15 minutes then dab the mozzarella with the paper towel to remove any additional moisture.\n" +
            "5. Bake the pizza: When the oven is ready, dust a pizza peel with cornmeal or semolina flour. (If you don’t have a pizza peel, you can use a rimless baking sheet or the back of a rimmed baking sheet. But a pizza peel is well worth the investment!) Stretch the dough into a circle; see How to Stretch Pizza Dough for instructions. Then gently place the dough onto the pizza peel. \n" +
            "6. Spread a thin layer of the pizza sauce over the dough, using about ¼ to ⅓ cup. Add the mozzarella cheese. Top with a thin layer of fresh grated Parmesan cheese and a few pinches of kosher salt.\n" +
            "7. Use the pizza peel to carefully transfer the pizza onto the preheated pizza stone. Bake the pizza until the cheese and crust are nicely browned, about 5 to 7 minutes in the oven (or 1 minute in a pizza oven).\n" +
            "8. Allow the pizza to cool for a minute or two before adding the basil on top (whole leaves, lightly torn, or thinly sliced). Slice into pieces and serve immediately.";

    public static final String HOMEMADE_CHEESE_PIZZA_TITLE = "Homemade cheese pizza";
    public static final String HOMEMADE_CHEESE_PIZZA_DESCRIPTION = "There’s nothing we love more than helping you make the best homemade pizza ever. We’ve got tons of pizza topping ideas from classic Margherita pizza to taco pizza, But there’s something so satisfying about a good old cheese pizza. Here’s your favorite delivery cheese pizza, but exactly 1 million times better. The sauce is extra tomato-y, the cheese is extra cheesy, and the crust is perfectly chewy. Want to know our secrets?";
    public static final String HOMEMADE_CHEESE_PIZZA_RECIPE = "1. Make the pizza dough: Follow the Best Pizza Dough recipe to prepare the dough. (This takes about 15 minutes to make and 45 minutes to rest.)\n" +
            "2. Place a pizza stone in the oven and preheat to 500°F. OR preheat your pizza oven (here’s the pizza oven we use).\n" +
            "3. Make the pizza sauce: Make the Easy Pizza Sauce.\n" +
            "4. Prepare the toppings: Slice or tear the fresh mozzarella into small pieces. \n" +
            "5. Bake the pizza: When the oven is ready, dust a pizza peel with cornmeal or semolina flour. (If you don’t have a pizza peel, you can use a rimless baking sheet or the back of a rimmed baking sheet. But a pizza peel is well worth the investment!) Stretch the dough into a circle; see How to Stretch Pizza Dough for instructions. Then gently place the dough onto the pizza peel.\n" +
            "6. Spread the pizza sauce over the dough using the back of a spoon to create a thin layer. Add the pieces of fresh mozzarella cheese evenly across the dough, then top with the shredded mozzarella cheese. Sprinkle evenly with the garlic powder, dried oregano, and a few pinches of kosher salt.\n" +
            "7. Use the pizza peel to carefully transfer the pizza onto the preheated pizza stone. Bake the pizza until the cheese and crust are nicely browned, about 5 to 7 minutes in the oven (or 1 minute in a pizza oven). Slice into pieces and serve immediately.";

    public static final String TACO_PIZZA_TITLE = "Taco pizza";
    public static final String TACO_PIZZA_DESCRIPTION = "Are you a taco pizza fan? Here at A Couple Cooks, Alex and I have spent years honing our best Italian-style pizza dough and the tastiest pizza sauce. We’ve even traveled to Italy for research. But our new best pizza recipe is not Italian at all. Yes, it’s taco pizza! That’s artisan style Italian crust on bottom, straight up delivery-style taco pizza on the top. It’s insanely good. And oh yeah: it’s topped with crunchy tortilla chips and drizzled with creamy homemade ranch. Here’s how to make it!";
    public static final String TACO_PIZZA_RECIPE = "1. Make the pizza dough: Follow the Best Pizza Dough recipe to prepare the dough. (This takes about 15 minutes to make and 45 minutes to rest.)\n" +
            "2. Place a pizza stone in the oven and preheat to 500°F. OR preheat your pizza oven (here’s the pizza oven we use).\n" +
            "3. Prepare the toppings: Taste the refried beans: if needed, mix in a pinch or two of cumin and a pinch of kosher salt. (Ours were already well seasoned.) Thinly slice the green onion. Chop the romaine lettuce. Chop the tomatoes.\n" +
            "4. Bake the pizza: When the oven is ready, dust a pizza peel with cornmeal or semolina flour. (If you don’t have a pizza peel, you can use a rimless baking sheet or the back of a rimmed baking sheet. But a pizza peel is well worth the investment!) Stretch the dough into a circle; see How to Stretch Pizza Dough for instructions. Then gently place the dough onto the pizza peel.\n" +
            "5. Spread the refried beans over the dough using a spatula to create a thin layer. Add the cheddar cheese, then top with black olives and half of the green onions. Top with a pinch of kosher salt.\n" +
            "6. Use the pizza peel to carefully transfer the pizza onto the preheated pizza stone. Bake the pizza until the cheese and crust are nicely browned, about 5 to 7 minutes in the oven (or 1 minute in a pizza oven).\n" +
            "7. Top with the reserved green onions, chopped tomatoes and romaine, and crumbled tortilla chips. Drizzle with ranch dressing and if desired, sprinkle with hot sauce. Slice into pieces and serve immediately.";

    public static final String SPANISH_ARTICHOKE_PIZZA_TITLE = "Spanish artichoke pizza";
    public static final String SPANISH_ARTICHOKE_PIZZA_DESCRIPTION = "What’s not to love about the iconic spinach artichoke party dip? That creamy, gooey cheese and tang from the artichokes make it some kind of addictive substance. We riffed on the classic for one of our first big “hits” in 2010: this spinach artichoke grilled cheese. Many years later, we’re here to riff on concept and make it into a pizza. Please meet, our spinach artichoke pizza. Gooey, savory, and tangy, it tastes like that popular dip on top of pizza crust. Who could resist it?";
    public static final String SPANISH_ARTICHOKE_PIZZA_RECIPE = "1. Make the pizza dough: Follow the Best Pizza Dough recipe to prepare the dough. (This takes about 15 minutes to make and 45 minutes to rest.)\n" +
            "2. Place a pizza stone in the oven and preheat to 500°F. OR preheat your pizza oven (here’s the pizza oven we use).\n" +
            "3. Prepare the toppings: Mince the garlic. In a small skillet, heat the olive oil, then add the garlic and saute for about 30 seconds. Add the spinach and cook for 2 to 3 minutes until wilted. Add the chopped artichokes for 1 minute. Remove from the heat.\n" +
            "4. Bake the pizza: When the oven is ready, dust a pizza peel with cornmeal or semolina flour. (If you don’t have a pizza peel, you can use a rimless baking sheet or the back of a rimmed baking sheet. But a pizza peel is well worth the investment!) Stretch the dough into a circle; see How to Stretch Pizza Dough for instructions. Then gently place the dough onto the pizza peel. \n" +
            "5. Brush the dough with a thin layer of olive oil. Then spread on the mozzarella cheese in an even layer, and place the spinach artichoke mixture on top. Top with the Pecorino Romano or Parmesan cheese and a few pinches of kosher salt.\n" +
            "6. Use the pizza peel to carefully transfer the pizza onto the preheated pizza stone. Bake the pizza until the cheese and crust are nicely browned, about 5 to 7 minutes in the oven (or 1 minute in a pizza oven). Slice into pieces and serve immediately.";

    public static final String QUATTRO_FORMAGGI_PIZZA_TITLE = "Quattro formaggi pizza";
    public static final String QUATTRO_FORMAGGI_PIZZA_DESCRIPTION = "Here’s a pie that’s one of the Italian greats: Quattro Formaggi! This classic Italian combination of four cheeses is popular for a reason: combine each flavor and texture and it makes one completely irresistible slice! There’s the melty mozzarella, sharp and salty Parmesan and Pecorino cheese, and the subtle funk of gorgonzola. Combine it all on pillowy pizza crust with zingy pizza sauce and it’s a match made in pizza heaven.";
    public static final String QUATTRO_FORMAGGI_PIZZA_RECIPE = "1. Make the pizza dough: Follow the Best Pizza Dough, Thin Crust Pizza Dough or Pizza Oven Dough recipes to prepare the dough. (This takes about 15 minutes to make and 45 minutes to rest.)\n" +
            "2. Place a pizza stone in the oven and preheat to 500°F. OR preheat your pizza oven (here’s the pizza oven we use).\n" +
            "3. Make the pizza sauce: Make the Homemade Pizza Sauce. (You’ll use about ½ cup for the pizza; reserve the remaining sauce and refrigerate for up to 1 week.)\n" +
            "4. Bake the pizza: When the oven is ready, dust a pizza peel with cornmeal or semolina flour. (If you don’t have a pizza peel, you can use a rimless baking sheet or the back of a rimmed baking sheet. But a pizza peel is well worth the investment!) Stretch the dough into a circle; see How to Stretch Pizza Dough for instructions. Then gently place the dough onto the pizza peel.\n" +
            "5 .Spread a thin layer of the pizza sauce over the dough. Add the mozzarella cheese, then sprinkle with the Pecorino Romano, Parmesan and gorgonzola cheese. \n" +
            "6. Use the pizza peel to carefully transfer the pizza onto the preheated pizza stone. Bake the pizza until the cheese and crust are nicely browned, about 5 to 7 minutes in the oven (or 1 to 2 minutes in a pizza oven).\n" +
            "7 .Allow the pizza to cool for a minute or two before slicing into pieces. Serve immediately.";

    public static final String RED_PEPPER_PIZZA_TITLE = "Red Pepper Pizza with Feta";
    public static final String RED_PEPPER_PIZZA_DESCRIPTION = "Need some pizza night ideas? Here’s an idea that’s so simple but tastes like it’s from your favorite pizza joint: this red pepper pizza with feta and oregano! First stir together our famous easy pizza sauce, which requires just 5 ingredients for its garlicky tomato flavor. Then top with mozzarella cheese, jarred roasted red pepper strips and salty feta cheese. Baked until the crust is golden and showered with fresh oregano, it’s one unforgettable pie.";
    public static final String RED_PEPPER_PIZZA_RECIPE = "1. Make the pizza dough: Follow the Best Pizza Dough, Thin Crust Pizza Dough or Pizza Oven Dough recipes to prepare the dough. (This takes about 15 minutes to make and 45 minutes to rest.)\n" +
            "2. Place a pizza stone in the oven and preheat to 500°F. OR preheat your pizza oven (here’s the pizza oven we use).\n" +
            "3 .Make the pizza sauce: Make the Homemade Pizza Sauce. (You’ll use about ½ cup for the pizza; reserve the remaining sauce and refrigerate for up to 1 week.)\n" +
            "4. Bake the pizza: When the oven is ready, dust a pizza peel with cornmeal or semolina flour. (If you don’t have a pizza peel, you can use a rimless baking sheet or the back of a rimmed baking sheet. But a pizza peel is well worth the investment!) Stretch the dough into a circle; see How to Stretch Pizza Dough for instructions. Then gently place the dough onto the pizza peel.\n" +
            "5 .Spread a thin layer of the pizza sauce over the dough. Add the mozzarella cheese. Add the red pepper strips and sprinkle with feta cheese. \n" +
            "6 .Use the pizza peel to carefully transfer the pizza onto the preheated pizza stone. Bake the pizza until the cheese and crust are nicely browned, about 5 to 7 minutes in the oven (or 1 to 2 minutes in a pizza oven).\n" +
            "7 .Allow the pizza to cool for a minute or two before adding the fresh oregano leaves. Slice into pieces and serve immediately.";

    public static final String GREEK_PIZZA_TITLE = "Greek Pizza with Feta";
    public static final String GREEK_PIZZA_DESCRIPTION = "Here’s a pizza topping idea that always gets rave reviews, with its smattering of colorful vegetables and hearty flavor: this Greek Pizza with Feta! There’s nothing better than the combination of tangy artichoke hearts, refreshing bursts of tomato, garlicky spinach, and salty olives and feta. We love a great veggie pizza, and this one is what we turn to most often. It’s destined to be the smash hit of your pizza night!";
    public static final String GREEK_PIZZA_RECIPE = "1. Make the pizza dough: Follow the Best Pizza Dough, Thin Crust Pizza Dough or Pizza Oven Dough recipes to prepare the dough. (This takes about 15 minutes to make and 45 minutes to rest.)\n" +
            "2. Place a pizza stone in the oven and preheat to 500°F. OR preheat your pizza oven (here’s the pizza oven we use).\n" +
            "3. Make the pizza sauce: Make the Homemade Pizza Sauce. (You’ll use about ⅓ cup for the pizza; reserve the remaining sauce and refrigerate for up to 1 week.)\n" +
            "4. Prepare the toppings: Warm the olive oil in small skillet. Add the spinach, 1 pinch salt, and 1 pinch garlic powder. Sauté over medium heat for 2 minutes until the spinach is wilted. Half the Kalamata olives, chop the artichoke hearts, thinly slice the red onion, and quarter the cherry tomatoes. \n" +
            "5. Bake the pizza: When the oven is ready, dust a pizza peel with cornmeal or semolina flour. (If you don’t have a pizza peel, you can use a rimless baking sheet or the back of a rimmed baking sheet. But a pizza peel is well worth the investment!) Stretch the dough into a circle; see How to Stretch Pizza Dough for instructions. Then gently place the dough onto the pizza peel.\n" +
            "6. Spread a thin layer of the pizza sauce over the dough. Add the mozzarella cheese. Top with the spinach, olives, artichoke, red onion, and tomatoes. Sprinkle with the feta cheese and dried oregano. Add a few pinches of kosher salt and some fresh ground pepper, to taste.\n" +
            "7. Use the pizza peel to carefully transfer the pizza onto the preheated pizza stone. Bake the pizza until the cheese and crust are nicely browned, about 5 to 7 minutes in the oven (or 1 to 2 minutes in a pizza oven).\n" +
            "8. Allow the pizza to cool for a minute or two before adding the basil on top (whole leaves, lightly torn, or thinly sliced). Slice into pieces and serve immediately.";

    public static final String OLIVE_PIZZA_TITLE = "Olive Pizza";
    public static final String OLIVE_PIZZA_DESCRIPTION = "Here’s a pizza topping combination that’s stunningly simple and one of the best pies around. Try this Olive Pizza! The simpler the better with Italian cuisine, and we’ve found that with pizza, a few curated ingredients can make magic. Here a mix of briny green and black olives interplay with thin slivers of red onion, pops of salty capers, and gooey mozzarella cheese. It’s one dream pie for olive lovers! We couldn’t get enough of this pie: the flavor is surprisingly greater than the sum of its parts.";
    public static final String OLIVE_PIZZA_RECIPE = "1. Make the pizza dough: Follow the Best Pizza Dough, Thin Crust Pizza Dough or Pizza Oven Dough recipes to prepare the dough. (This takes about 15 minutes to make and 45 minutes to rest.)\n" +
            "2. Place a pizza stone in the oven and preheat to 500°F. OR preheat your pizza oven (here’s the pizza oven we use).\n" +
            "3. Make the pizza sauce: Make the Homemade Pizza Sauce. (You’ll use about ½ cup for the pizza; reserve the remaining sauce and refrigerate for up to 1 week.)\n" +
            "4. Bake the pizza: When the oven is ready, dust a pizza peel with cornmeal or semolina flour. (If you don’t have a pizza peel, you can use a rimless baking sheet or the back of a rimmed baking sheet. But a pizza peel is well worth the investment!) Stretch the dough into a circle; see How to Stretch Pizza Dough for instructions. Then gently place the dough onto the pizza peel.\n" +
            "5. Spread a thin layer of the pizza sauce over the dough. Add the mozzarella cheese, then sprinkle with the Parmesan cheese. Top with the sliced olives, red onion, and capers, then sprinkle with dried oregano.\n" +
            "6. Use the pizza peel to carefully transfer the pizza onto the preheated pizza stone. Bake the pizza until the cheese and crust are nicely browned, about 5 to 7 minutes in the oven (or 1 to 2 minutes in a pizza oven).\n" +
            "7. Allow the pizza to cool for a minute or two before slicing into pieces. Serve immediately.";

    public static final String EVERYTHING_BASIL_PIZZA_TITLE = "Everything Basil Pizza";
    public static final String EVERYTHING_BASIL_PIZZA_DESCRIPTION = "Are you basil obsessed? There’s nothing better than the peppery fresh flavor of this bright green herb. So get ready to take everything that’s incredible about basil and eat it as a pizza topping. That’s right: Everything Basil Pizza! (Get it? Sounds a lot like…this!) That means garlicky, thick homemade basil pesto slathered onto perfect pizza dough, topped with gooey mozzarella and a huge handful of fresh basil leaves. It’s the brightest green, tastiest basil pizza you’ll ever make.";
    public static final String EVERYTHING_BASIL_PIZZA_RECIPE = "1. Make the pizza dough: Follow the Best Pizza Dough or Thin Crust Dough recipe to prepare the dough. (This takes about 15 minutes to make and 45 minutes to rest.)\n" +
            "2. Place a pizza stone in the oven and preheat to 500°F. OR preheat your pizza oven (here’s the pizza oven we use).\n" +
            "3. Prepare the toppings: Make the Best Basil Pesto (or Cashew Pesto, Walnut Pesto, or Vegan Pesto). Thinly slice the fresh basil (or keep it whole if you like).\n" +
            "4. Bake the pizza: When the oven is ready, dust a pizza peel with cornmeal or semolina flour. (If you don’t have a pizza peel, you can use a rimless baking sheet or the back of a rimmed baking sheet. But a pizza peel is well worth the investment!) Stretch the dough into a circle; see How to Stretch Pizza Dough for instructions. Then gently place the dough onto the pizza peel.\n" +
            "5. Spoon the pesto onto the dough and spread it out with the back of the spoon. Then top with the mozzarella cheese in an even layer, then the Parmesan cheese. Add a pinch of dried basil and if you like, a sprinkle of kosher salt. (Most pesto is salty enough, but it depends on your pesto and cheese.)\n" +
            "6. Use the pizza peel to carefully transfer the pizza onto the preheated pizza stone. Bake the pizza until the cheese and crust are nicely browned, about 5 to 7 minutes in the oven (or 1 minute in a pizza oven).\n" +
            "7. Top with the basil leaves. Slice into pieces and serve immediately.";

    public static final String GOAT_CHEESE_PIZZA_TITLE = "Everything Basil Pizza";
    public static final String GOAT_CHEESE_PIZZA_DESCRIPTION = "When it comes to pizza toppings, there’s one that is always, always a hit in our house. Goat cheese! This Goat Cheese Pizza is a true masterpiece, pairing soft pockets of chevre with tangy, garlicky tomato sauce. Shower it with a few sliced onions and a sprinkle of fresh basil, and we promise: the slices will be gone in a flash! This one is a massive crowd pleaser. And side bonus: our son loves it because it reminds us of the game Taco Cat Goat Cheese Pizza! (Perfect for game night?)";
    public static final String GOAT_CHEESE_PIZZA_RECIPE = "1. Make the pizza dough: Follow the Best Pizza Dough, Thin Crust Pizza Dough or Pizza Oven Dough recipes to prepare the dough. (This takes about 15 minutes to make and 45 minutes to rest.)\n" +
            "2. Place a pizza stone in the oven and preheat to 500°F. OR preheat your pizza oven (here’s the pizza oven we use).\n" +
            "3. Make the pizza sauce: Make the Homemade Pizza Sauce. (You’ll use about ⅓ cup for the pizza; reserve the remaining sauce and refrigerate for up to 1 week.)\n" +
            "4. Bake the pizza: When the oven is ready, dust a pizza peel with cornmeal or semolina flour. (If you don’t have a pizza peel, you can use a rimless baking sheet or the back of a rimmed baking sheet. But a pizza peel is well worth the investment!) Stretch the dough into a circle; see How to Stretch Pizza Dough for instructions. Then gently place the dough onto the pizza peel.\n" +
            "5. Spread a thin layer of the pizza sauce over the dough. Add the mozzarella cheese. Add the goat cheese in large dollops (be generous!). Sprinkle with the red onion slices and dried oregano. Add a few pinches of kosher salt and some fresh ground pepper, to taste.\n" +
            "6. Use the pizza peel to carefully transfer the pizza onto the preheated pizza stone. Bake the pizza until the cheese and crust are nicely browned, about 5 to 7 minutes in the oven (or 1 to 2 minutes in a pizza oven).\n" +
            "7. Allow the pizza to cool for a minute or two before adding the basil on top (whole leaves, lightly torn, or thinly sliced). Slice into pieces and serve immediately.";
}
